# Generated by Django 4.2 on 2024-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdstudent',
            name='ongoing',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
