# Generated by Django 4.2 on 2024-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_phdstudent_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdstudent',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
