# Generated by Django 4.2 on 2024-05-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_phdstudent_ongoing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingofficer',
            options={},
        ),
        migrations.RemoveField(
            model_name='pollingofficer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pollingofficer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pollingofficer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pollingofficer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pollingofficer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pollingofficer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pollingofficer',
            name='user_permissions',
        ),
    ]
