# Generated by Django 4.2 on 2024-05-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pollingofficer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingofficer',
            name='photo',
        ),
    ]
