# Generated by Django 4.2 on 2024-05-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestingCandidate',
            fields=[
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.student', to_field='roll_number')),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary - Cultural Board', 'General Secretary - Cultural Board'), ('General Secretary - Technical Board', 'General Secretary - Technical Board'), ('General Secretary - Sports Board', 'General Secretary - Sports Board')], max_length=36)),
                ('por_description', models.TextField()),
                ('manifesto', models.FileField(blank=True, null=True, upload_to='manifestos/')),
                ('is_approved', models.BooleanField(default=None)),
                ('vote_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.contestingcandidate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student', to_field='roll_number')),
            ],
        ),
    ]
