# Generated by Django 4.2 on 2024-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestingcandidate',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
