# Generated by Django 4.2 on 2024-05-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_contestingcandidate_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary - Cultural Board', 'General Secretary - Cultural Board'), ('General Secretary - Technical Board', 'General Secretary - Technical Board'), ('General Secretary - Sports Board', 'General Secretary - Sports Board')], default=None, max_length=36),
            preserve_default=False,
        ),
    ]
