# Generated by Django 4.2 on 2024-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_contestingcandidate_vote_count_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestingcandidate',
            old_name='is_approved',
            new_name='nomination_approved',
        ),
        migrations.AddField(
            model_name='contestingcandidate',
            name='faculty_approval_by',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contestingcandidate',
            name='nominated_by',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
